# Generated by Django 3.2.6 on 2022-03-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_choice_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_post']},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='account.question'),
        ),
    ]
