# Generated by Django 3.2.6 on 2022-03-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_candidate_results_user_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_names',
            name='candidate_results',
        ),
        migrations.AlterField(
            model_name='candidate_results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_names'),
        ),
    ]
